//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace CommonLibrary.CheckReg {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="CheckReg.WebServiceExamSoap")]
    public interface WebServiceExamSoap {
        
        // CODEGEN: 命名空间 http://tempuri.org/ 的元素名称 reg 以后生成的消息协定未标记为 nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/CheckReg", ReplyAction="*")]
        CommonLibrary.CheckReg.CheckRegResponse CheckReg(CommonLibrary.CheckReg.CheckRegRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetServiceTime", ReplyAction="*")]
        System.DateTime GetServiceTime();
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class CheckRegRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="CheckReg", Namespace="http://tempuri.org/", Order=0)]
        public CommonLibrary.CheckReg.CheckRegRequestBody Body;
        
        public CheckRegRequest() {
        }
        
        public CheckRegRequest(CommonLibrary.CheckReg.CheckRegRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class CheckRegRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string reg;
        
        public CheckRegRequestBody() {
        }
        
        public CheckRegRequestBody(string reg) {
            this.reg = reg;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class CheckRegResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="CheckRegResponse", Namespace="http://tempuri.org/", Order=0)]
        public CommonLibrary.CheckReg.CheckRegResponseBody Body;
        
        public CheckRegResponse() {
        }
        
        public CheckRegResponse(CommonLibrary.CheckReg.CheckRegResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class CheckRegResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string CheckRegResult;
        
        public CheckRegResponseBody() {
        }
        
        public CheckRegResponseBody(string CheckRegResult) {
            this.CheckRegResult = CheckRegResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface WebServiceExamSoapChannel : CommonLibrary.CheckReg.WebServiceExamSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class WebServiceExamSoapClient : System.ServiceModel.ClientBase<CommonLibrary.CheckReg.WebServiceExamSoap>, CommonLibrary.CheckReg.WebServiceExamSoap {
        
        public WebServiceExamSoapClient() {
        }
        
        public WebServiceExamSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public WebServiceExamSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WebServiceExamSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WebServiceExamSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        CommonLibrary.CheckReg.CheckRegResponse CommonLibrary.CheckReg.WebServiceExamSoap.CheckReg(CommonLibrary.CheckReg.CheckRegRequest request) {
            return base.Channel.CheckReg(request);
        }
        
        public string CheckReg(string reg) {
            CommonLibrary.CheckReg.CheckRegRequest inValue = new CommonLibrary.CheckReg.CheckRegRequest();
            inValue.Body = new CommonLibrary.CheckReg.CheckRegRequestBody();
            inValue.Body.reg = reg;
            CommonLibrary.CheckReg.CheckRegResponse retVal = ((CommonLibrary.CheckReg.WebServiceExamSoap)(this)).CheckReg(inValue);
            return retVal.Body.CheckRegResult;
        }
        
        public System.DateTime GetServiceTime() {
            return base.Channel.GetServiceTime();
        }
    }
}
